controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

test:
    path: /test
    controller:  App\Controller\TestController::indexAction